#include QMK_KEYBOARD_H

enum layers{_BASE,_L1,_L2,_L3};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS]={
[_BASE]=LAYOUT(
KC_1,KC_2,KC_3,
KC_4,KC_5,KC_6,
KC_7,KC_8,QK_BOOT),
[_L1]=LAYOUT(
KC_F1,KC_F2,KC_F3,
KC_F4,KC_F5,KC_F6,
KC_F7,KC_F8,QK_BOOT),
[_L2]=LAYOUT(
RGB_TOG,RGB_MOD,RGB_HUI,
RGB_HUD,RGB_SAI,RGB_SAD,
RGB_VAI,RGB_VAD,QK_BOOT),
[_L3]=LAYOUT(
KC_MPRV,KC_MPLY,KC_MNXT,
KC_VOLD,KC_MUTE,KC_VOLU,
_______,_______,QK_BOOT)
};
